### ISSUE TITLE
builds should automatically get uploaded to pypi

### ISSUE THREAD

**Issue by dvopsway** [dvopsway/sshmux#10]
builds should automatically get uploaded to pypi

**Comment by dvopsway** [comment]
Automated build deployment now integrated after https://github.com/dvopsway/sshmux/commit/a2284b69f997b1449f521481b436e6d7cd0c9a71

**Comment by ghost** [comment]
hi @dvopsway 

I think it is better to work with milestones at github [releases](https://help.github.com/articles/about-releases/) thiks way we can have a feature complete project released to pypi instead of every single commit.

Maybe create a first milestone with some issues like python3 and some new features like more unittests. See [this](https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/) and [this](https://guides.github.com/features/issues/) for more about milestones

**Comment by dvopsway** [comment]
@rjrhaverkamp good idea I have created our first milestone https://github.com/dvopsway/sshmux/milestone/1. pypi deployments only work if commit is tagged, which we will do once milestone is achieved. Let me know your thoughts.

**Comment by dvopsway** [comment]
This has been done.
